const myProjects = [
  {
    id: 1,
    name: "Run Buddy",
    liveURL: "https://teresacabell.github.io/run-buddy/",
    image: require("./assets/images/screenshot-budget.png"),
    gURL: "https://github.com/teresacabell/run-buddy",
    tech: "HTML, CSS",
    style: "run-buddy",
  },
  {
    id: 2,
    name: "Flying Dollars",
    liveURL: "https://jasonvissage.github.io/Flying-Dollars/",
    image: require("./assets/images/screenshot-weather.png"),
    gURL: "https://github.com/jasonvissage/Flying-Dollars",
    tech: "HTML, CSS, JavaScript, Bulma",
    style: "flying-dollars",
  },
  {
    id: 3,
    name: "Old Fashioned",
    liveURL: "https://damp-temple-66157.herokuapp.com/",
    image: require("./assets/images/screenshot-drinks.jpg"),
    gURL: "https://github.com/paul88vera/Old-Fashioned/",
    tech: "HTML, CSS, JavaScript, Express, mysql2",
    style: "old-fashioned",
  },
  {
    id: 4,
    name: "Budget Tracker",
    liveURL: "https://secure-eyrie-73081.herokuapp.com/",
    image: require("./assets/images/screenshot-budget.png"),
    gURL: "https://github.com/teresacabell/symmetrical-bassoon",
    tech: "JavaScript, HTML, CSS",
    style: "budget-tracker",
  },
  {
    id: 5,
    name: "Work Day Scheduler",
    liveURL: "https://teresacabell.github.io/super-disco/",
    image: require("./assets/images/screenshot-scheduler.png"),
    gURL: "https://github.com/teresacabell/super-disco",
    tech: "HTML, JavaScript, CSS",
    style: "work-day-scheduler",
  },
  {
    id: 6,
    name: "Robot Gladiators",
    liveURL: "https://teresacabell.github.io/robot-gladiators/",
    image: require("./assets/images/screenshot-robot.png"),
    gURL: "https://github.com/teresacabell/robot-gladiators",
    tech: "HTML, JavaScript",
    style: "robot-gladiators",
  },
];

export default myProjects;
